using System;
using System.Collections.Generic;

namespace CopaCmd.AttnErp.Models
{
    public partial class Cust
    {
        public string CusNo { get; set; } = null!;
        public string? Idx2 { get; set; }
        public string? CusAre { get; set; }
        public string? MasCus { get; set; }
        public string? ObjId { get; set; }
        public string? Name { get; set; }
        public string? Snm { get; set; }
        public string? NmEng { get; set; }
        public short? PayDd { get; set; }
        public string? ClsMth { get; set; }
        public short? ClsDd { get; set; }
        public short? MmEnd { get; set; }
        public short? ChkDd { get; set; }
        public string? UniNo { get; set; }
        public string? BosNm { get; set; }
        public string? CntJob1 { get; set; }
        public string? CntMan1 { get; set; }
        public string? CntJob2 { get; set; }
        public string? CntMan2 { get; set; }
        public string? AccMan { get; set; }
        public string? Sal { get; set; }
        public string? Tel1 { get; set; }
        public string? Tel2 { get; set; }
        public string? Fax { get; set; }
        public string? Adr1 { get; set; }
        public string? Adr2 { get; set; }
        public string? AdrEng { get; set; }
        public string? Zip { get; set; }
        public decimal? LimNr { get; set; }
        public decimal? LimNc { get; set; }
        public string? CrdId { get; set; }
        public string? InvId { get; set; }
        public string? Id1Tax { get; set; }
        public string? Id2Tax { get; set; }
        public string? Cls1 { get; set; }
        public string? Cls2 { get; set; }
        public DateTime? StrDd { get; set; }
        public DateTime? EndDd { get; set; }
        public string? Cur { get; set; }
        public string? CrdNrNc { get; set; }
        public string? Rem { get; set; }
        public string? EMail { get; set; }
        public string? SendMth { get; set; }
        public string? SendWh { get; set; }
        public string? BnkName { get; set; }
        public string? IdCode { get; set; }
        public string? CusLevel { get; set; }
        public string? IncCheck { get; set; }
        public decimal? LsRto { get; set; }
        public string? Compnet { get; set; }
        public DateTime? CompDd { get; set; }
        public decimal? Capsum { get; set; }
        public decimal? Busisum { get; set; }
        public int? Salms { get; set; }
        public string? Businote { get; set; }
        public string? Workitm { get; set; }
        public string? MainPrd { get; set; }
        public string? ChkCrd { get; set; }
        public string? SFlag { get; set; }
        public decimal? Initnum { get; set; }
        public string? Notify { get; set; }
        public string? Broker { get; set; }
        public string? Vessel { get; set; }
        public string? LoadingPort { get; set; }
        public string? DisPort { get; set; }
        public string? ManuPlace { get; set; }
        public string? Epaper { get; set; }
        public string? TranRec { get; set; }
        public string? Pswd { get; set; }
        public string? PswdHit { get; set; }
        public string? PswdAns { get; set; }
        public DateTime? ApplyDd { get; set; }
        public string? BizDsc { get; set; }
        public string? Country { get; set; }
        public string? BankNo { get; set; }
        public string? AccNoAr { get; set; }
        public string? AccNoAp { get; set; }
        public string? AccNoR0 { get; set; }
        public string? AccNoP0 { get; set; }
        public string? SoCrd { get; set; }
        public string? FpName { get; set; }
        public string? ChkFax { get; set; }
        public decimal? RtoTax { get; set; }
        public string? ChkCusIdx { get; set; }
        public string? CyId { get; set; }
        public string? RegistCode { get; set; }
        public string? CorpId { get; set; }
        public string? MCust { get; set; }
        public string? SalNo { get; set; }
        public string? ChkDep { get; set; }
        public decimal? RtoKk { get; set; }
        public string? Dep { get; set; }
        public decimal? RtoFl { get; set; }
        public decimal? RtoYl { get; set; }
        public string? Dep1 { get; set; }
        public string? Usr { get; set; }
        public string? ChkInclude { get; set; }
        public string? ChkIrp { get; set; }
        public string? ChkTrp { get; set; }
        public string? ChkMan { get; set; }
        public DateTime? ClsDate { get; set; }
        public string? ChkPay1 { get; set; }
        public short? PayDays { get; set; }
        public string? PayFlag { get; set; }
        public string? ChkPay2 { get; set; }
        public string? ChkPay3 { get; set; }
        public decimal? AmtnMaxPay { get; set; }
        public string? ChkQk { get; set; }
        public decimal? AmtnQk { get; set; }
        public string? Usr1 { get; set; }
        public DateTime? SysDate { get; set; }
        public decimal? RtoDiscnt { get; set; }
        public string? ChkIrp2 { get; set; }
        public string? Logon { get; set; }
        public string? WhNo { get; set; }
        public string? StopOrder { get; set; }
        public string? RtnCtrl { get; set; }
        public string? DrpId { get; set; }
        public string? Upr4Id { get; set; }
        public string? YhWh1 { get; set; }
        public string? YhWh2 { get; set; }
        public string? AccNoIr { get; set; }
        public string? AccNoIp { get; set; }
        public string? B2cId { get; set; }
        public string? CardNo { get; set; }
        public byte[]? UpDd { get; set; }
        public short? PrtweeksPo { get; set; }
        public short? SoweeksPo { get; set; }
        public string? LangId { get; set; }
        public string? ChkDrp1 { get; set; }
        public string? ChkDrp2 { get; set; }
        public string? ChkDrp3 { get; set; }
        public string? SrvNo { get; set; }
        public string? CusIdx { get; set; }
        public string? XnNo { get; set; }
        public int? Cwork { get; set; }
        public string? ChkBarcode { get; set; }
        public string? AccNoZp { get; set; }
        public string? HmId { get; set; }
        public string? PswdPay { get; set; }
        public decimal? AmtnFl { get; set; }
        public decimal? AmtnFled { get; set; }
        public string? ChkSbrto { get; set; }
        public string? DeproNo { get; set; }
        public decimal? RtoFqsk { get; set; }
        public string? DateflagFqsk { get; set; }
        public DateTime? DateFqsk { get; set; }
        public int? QsFqsk { get; set; }
        public string? LocalId { get; set; }
        public int? RuleId { get; set; }
        public string? Tel1Code { get; set; }
        public string? UniNo2 { get; set; }
        public string? FpName2 { get; set; }
        public string? CodeName { get; set; }
        public string? ChkKd { get; set; }
        public string? WsCusNo { get; set; }
        public string? AutoCasnChk { get; set; }
        public string? NsrCode { get; set; }
        public string? NamePy { get; set; }
        public string? CusSrc { get; set; }
        public string? AccNoAr2 { get; set; }
        public string? AccNoAp2 { get; set; }
        public int? VisitLimit { get; set; }
        public DateTime? BbDd { get; set; }
        public DateTime? SoDd { get; set; }
        public string? MobId { get; set; }
        public string? TtTypeSet { get; set; }
        public string? ExTrdId { get; set; }
        public string? ImTrdId { get; set; }
        public string? CusNoKd { get; set; }
        public string? ChkZhangId2 { get; set; }
        public string? PjsqWh { get; set; }
        public string? JdNo { get; set; }
        public string? FpType { get; set; }
        public string? ChkCx { get; set; }
        public string? ChkMinXf { get; set; }
        public string? BilMinXf { get; set; }
        public string? ChkTypeMinxf { get; set; }
        public decimal? AmtnMinXf { get; set; }
        public string? RemS { get; set; }
        public string? DepFh { get; set; }
        public string? WhFh { get; set; }
        public string? CusFh { get; set; }
        public string? ChkO2oFx { get; set; }
        public string? ChkMall { get; set; }
        public string? FxLevel { get; set; }
        public string? DjLc { get; set; }
        public string? DjPay { get; set; }
        public string? DjSq { get; set; }
        public decimal? AmtnDj { get; set; }
        public string? LimNrType { get; set; }
        public string? ChkFullPay { get; set; }
        public string? ChkCk { get; set; }
        public string? Iscustkey { get; set; }
        public string? SupLevel { get; set; }
        public string? BrdNo { get; set; }
        public string? CaNo { get; set; }
        public string? Ca1No { get; set; }
        public string? NbrdNo { get; set; }
        public string? NcaNo { get; set; }
        public string? Nca1No { get; set; }
        public string? Interest { get; set; }
        public string? NszgFlag { get; set; }
        public string? BaccNo { get; set; }
        public string? ChkIndx1 { get; set; }
        public string? BankName { get; set; }
        public string? SCode { get; set; }
        public string? DjYe { get; set; }
        public string? ChkFl { get; set; }
        public string? ZqBtCtrl { get; set; }
        public string? ChkPrdBt { get; set; }
        public DateTime? TzbhDd { get; set; }
        public string? TzbhBilId { get; set; }
        public DateTime? TzfhDd { get; set; }
        public string? TzfhBilId { get; set; }
        public string? ChkSkipLim { get; set; }
        public string? YhType { get; set; }
        public string? Tempflag { get; set; }
        public string? B2btype { get; set; }
        public string? Iscoop { get; set; }
        public string? CkUsewh { get; set; }
        public string? UsewhId { get; set; }
        public string? ChkTh { get; set; }
        public int? PrePsdays { get; set; }
        public string? ChkPc { get; set; }
        public string? ChkTw { get; set; }
        public string? ChkDrp4 { get; set; }
        public DateTime? LastCntDd { get; set; }
        public DateTime? RcCntDd { get; set; }
        public DateTime? SjCntDd { get; set; }
        public DateTime? BfCntDd { get; set; }
        public DateTime? ModifyDd { get; set; }
        public string? ModifyMan { get; set; }
        public string? TiFromPo { get; set; }
        public string? TiFromTw { get; set; }
        public string? ChkShgk { get; set; }
        public int? ShzqM { get; set; }
        public string? LostType { get; set; }
        public int? LostItmes { get; set; }
        public string? ChkTzsh { get; set; }
        public string? LostCtype { get; set; }
        public string? CustBbTypeId { get; set; }
        public string? FlagTaxchgI { get; set; }
        public string? FlagTaxchgO { get; set; }
        public decimal? RtoDiscntLevel { get; set; }
        public string? GdzWebdz { get; set; }
        public string? GdzWebflow { get; set; }
        public string? TiFrom { get; set; }
        public string? TiFromId { get; set; }
        public int? CounId { get; set; }
        public string? AddIdNo { get; set; }
        public string? ChkMinCg { get; set; }
        public string? BilMinCg { get; set; }
        public string? ChkTypeMincg { get; set; }
        public decimal? AmtnMinCg { get; set; }
        public string? AppNameData { get; set; }
        public string? WmsShlcPo { get; set; }
        public string? WmsShlcTw { get; set; }
        public string? BizDsc1 { get; set; }
        public byte[]? PhotoPic { get; set; }
    }
}
